/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({

    requires: [
        'Chart.ux.Highmaps',
        'Chart.ux.Highcharts.MapSerie',
        'Chart.ux.Highcharts.MapLineSerie',
        'Chart.ux.Highcharts.MapPointSerie',
        'Chart.ux.Highcharts.MapBubbleSerie',
        'Chart.ux.Highcharts.LineSerie',
        'Chart.ux.Highcharts.AreaSerie',
        'Ext.layout.container.Border',
        'Ext.layout.container.Card',
        'Chart.ux.Highcharts.HeatmapSerie',
        'Chart.ux.Highcharts.PieSerie'
    ],
    models: [
        'PopDensity',
        'MapData2',
        'PopDensity1',
        'Path',
        'XYCoord',
        'Population',
        'PopulationHistory',
        'Value',
        'USStates',
        'Drilldown',
        'Heatmap',
        'USMap',
        'Vote'
    ],
    stores: [
        'PopDensity',
        'PopDensity1',
        'MapData2',
        'MeuseAreas',
        'MeuseBasin',
        'Meuse',
        'Tributaries',
        'Borders',
        'Cities',
        'WorldPopulation',
        'PopulationHistory',
        'USCountiesMap',
        'USCountiesData',
        'USCountiesBorders',
        'USStates',
        'Heatmap',
        'Drilldown',
        'USMap',
        'Vote'
    ],
    views: [
        'MainView',
        'SetValue'
    ],
    controllers: [
        'Navigation'
    ],
    name: 'Demo',

    launch: function() {
        Ext.create('Demo.view.MainView');
    }

});
