/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Demo.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.panel.Tool'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 241,
                    title: 'Main Demos',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'main_map_demos',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'chart_map',
                                    text: 'Chart & Map working along'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'us_counties',
                                    text: 'US Unemployment Counties (grid lines style)'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'popup_graph',
                                    text: 'Data Classes & Popup graphs'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'drilldown',
                                    text: 'US Map Drilldown (Store\'s Sync Load)'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'heatmap',
                                    text: 'Heat Map'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'empty_world',
                                    text: 'Empty World Map'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'pop_density',
                                    text: 'Population Density (Join By)'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mult_series',
                                    text: 'Multi Series (Map, Line, and Point)'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'bubble_series',
                                    text: 'Bubble Series'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'popup_menu',
                                    text: 'Popup Menu & Update Value Dialog'
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'ext_map_demos',
                            collapsible: false,
                            title: 'Extended Demos',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'pop_density_1',
                                    text: 'Population Density (mapData with store)'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'contentPanel',
                    itemId: 'contentPanel',
                    layout: 'card',
                    title: 'Demo',
                    tools: [
                        {
                            xtype: 'tool',
                            itemId: 'mytool',
                            type: 'help'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});